services:
  db:
    image: postgres:16-alpine
    container_name: desinvolt-db-dev
    env_file:
      - .env.dev
    volumes:
      - desinvolt-data-dev:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    image: desinvolt-app-dev
    container_name: desinvolt-app-dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - .env.dev
    ports:
      - "${PORT}:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["sh", "-c", "pnpm prisma generate && pnpm prisma migrate dev --name auto && pnpm dev"]
    restart: unless-stopped

volumes:
  desinvolt-data-dev:
