FROM node:20-alpine

WORKDIR /app


RUN apk add --no-cache libc6-compat bash git


COPY package.json pnpm-lock.yaml ./


RUN npm install -g pnpm


RUN pnpm install --frozen-lockfile

# RUN pnpm prisma generate

EXPOSE 3000