/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}", "./typography.css"],
  theme: {
    extend: {
      fontFamily: {
        roadRage: ["RoadRage", "sans-serif"],
        zingRust: ["ZingRustDemo", "sans-serif"],
        contrailOne: ["ContrailOne", "sans-serif"],
        overpass: ["Overpass", "sans-serif"],
      },
      fontSize: {
        "mobile-logo": "24px",
        "desktop-logo": "32px",
        headline: "36px",
        title: "24px",
        "title-sm": "16px",
        "subtitle-xl": "24px",
        "subtitle-lg": "20px",
        subtitle: "16px",
        "subtitle-sm": "12px",
        "paragraph-xl": "24px",
        "paragraph-lg": "18px",
        paragraph: "16px",
        "paragraph-sm": "12px",
        "paragraph-xs": "10px",
        button: "16px",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        "muted-second": "var(--muted-second)",
        "chart-1": "var(--color-chart-1)",
        "chart-2": "var(--color-chart-2)",
        "chart-3": "var(--color-chart-3)",
        "chart-4": "var(--color-chart-4)",
      },
    },
  },
  plugins: [],
};
